# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mean',
            name='word',
            field=models.ForeignKey(default='aaa', on_delete=django.db.models.deletion.CASCADE, related_name='means', to='deneme.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanicininkelimesi', to='deneme.Kullanici'),
        ),
    ]
